name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name : echocommand 
        run: echo "this is test"

      - name: multiline script
        run: |
          node -v
          npm -v
    
    
    
    