name: Terraform test flow

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.1
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.1
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.1
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.1
          tf_actions_subcommand: 'Plan'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.1
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"